### ISSUE TITLE
Update hello-world-angular sample to Angular versions ^15.0.0.0

### ISSUE THREAD

**Issue by nelak2** [microsoft/vscode-webview-ui-toolkit-samples#121]
### Describe the bug

When building the hello-world-angular sample per the instructions it fails as it is unable to resolve the Angular dependencies.

### To reproduce

npx degit microsoft/vscode-webview-ui-toolkit-samples/frameworks/hello-world-angular hello-world
cd hello-world
**npm run install:all** <- Fails on this step
npm run build:webview
code .

### Expected behavior

The sample project should build and run successfully

### Screenshots

![image](https://user-images.githubusercontent.com/1634216/205152858-684da3ef-c839-4623-8b3f-059bcb55a288.png)

### Desktop (please complete the following information):

-   OS Version: Windows 10 Home
-   Toolkit Version: npm 8.19.2

### Additional context

_Add any other context about the problem here._

**Comment by hawkticehurst** [comment]
Hey @nelak2, thanks for the bug report!

I looked into this during the last few weeks and found out that the problem likely has to do with a TypeScript versioning mismatch between what Angular v15 uses and what FAST uses (a technology we use to build the toolkit components).

[See more of that discussion here.](https://github.com/microsoft/fast/issues/6602#issuecomment-1382376870)

It means that a fix for using the toolkit in Angular v15 might, unfortunately, take a while. In the meantime, however, I just merged a PR that (among other things) reverts the hello-world-angular sample back to using Angular v13.

**Comment by hawkticehurst** [comment]
I will keep this issue open as a reminder to adopt a fix from FAST whenever it is released.

**Comment by hawkticehurst** [comment]
Hi @nelak2!

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) earlier this week on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
