### ISSUE TITLE
ALL HelloWorld samples improperly leak content (fail to properly dispose)

### ISSUE THREAD

**Issue by kahlkevin** [microsoft/vscode-webview-ui-toolkit-samples#122]
### Describe the bug

The HelloWorld samples, based on `HelloWorldPanel.ts`, appear to fail to properly dispose content.

This is caused by incorrectly registering  `null` for `thisArg` when signing up for `onDidDispose` notification. Later call to `this._panel.dispose()` throws unhandled exception (because `this` is `null`) resulting in bypass of the remainder of the cleanup logic.

 (See `constructor` implementation in `HelloWorldPanel.ts` across the various sub-projects.)

**NOTE** #102 submitted in October to address the problem in the basic sample, but problem exists in (at least) all of the HelloWorld samples too.

### To reproduce

1. Build and launch default/hello-world sample.
2. Open Developer Tools (Ctrl+Shift+I on Windows)
3. Run "Hello World: Show" command
4. Close the resulting panel.

Here you'll see unhandled exception stacktrace appear in the developer tools console. As a result, the second half of the disposal logic (the `while` loop) fails to run.

### Expected behavior

No null dereference, no exception, proper disposal.

### Desktop

-   OS Version: Windows 11, 22H2, build 22621.819
-   Toolkit Version: 1.2.0

### Additional context

Sample code is an especially bad place to maintain incorrect behavior since it's likely to be copied/pasted/reused many times over and in difficult-to-track ways.

@hawkticehurst

**Comment by kahlkevin** [comment]
The bad code is also shown on [this tutorial page](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/docs/getting-started.md) in the `vscode-webview-ui-toolkit` project.

**Comment by mainIdal** [comment]
I appreciate you reporting the bug. I awaited for PR #102 to be closed and resolved before announcing the bug to be sure I hadn't overlooked  any technical aspects.

**Comment by hawkticehurst** [comment]
Hey all! 

My apologies for not responding to this issue sooner. We're really tightly resourced on the toolkit at this time (myself and one other person split our time between this project and a bunch of others), so it's taken some time to get through my backlog of other todos

My plan is to address/resolve this issue before I leave for a holiday in the next 2 weeks 😊
