### ISSUE TITLE
webview angular assets/i18n/en.json access denied

### ISSUE THREAD

**Issue by lastnod** [microsoft/vscode-webview-ui-toolkit-samples#171]
### Describe the bug

en.json is called by main.ts in a webview but access is denied
i use angular framework
![image](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/8791187/7a9dec3c-49f9-4413-9869-9f6cdde5182b)
![image](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/8791187/4739483c-ba54-49db-ae69-6ad52f1809fe)

### To reproduce

use standard i18n module
![image](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/8791187/95f96b52-1339-4f7a-93eb-5b4c344f0662)

### Expected behavior

having status 200 :) on local ressources i tried : 
![image](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/8791187/bc121256-8fac-4d8c-9894-44eca5393734)
but it did'nt worked

### Desktop (please complete the following information):

-   OS Version: _[e.g. windows 11
-   Toolkit Version: "@vscode/webview-ui-toolkit": "^1.2.2"

### Additional context

_Add any other context about the problem here._

**Comment by hawkticehurst** [comment]
Hey @lastnod!

I'd wager this is an issue with the content security policies set up for the webview. If you started your project by using the hello-world angular sample, the CSP is set up to be as minimal as possible (following the security principle of least privilege) –– only styles (CSS) and scripts (JS) are configured to be allowed.

In the sample extension, CSP is set as a `<meta>` tag on [line 118](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/blob/main/frameworks/hello-world-angular/src/panels/HelloWorldPanel.ts#L118) in the `HelloWorldPanel.ts` file.

Would you mind sharing what your CSP looks like?

_p.s. this is also likely why the logo.png file is not loading, images are not configured in the CSP either._

**Comment by lastnod** [comment]
> Hey @lastnod!
> 
> I'd wager this is an issue with the content security policies set up for the webview. If you started your project by using the hello-world angular sample, the CSP is set up to be as minimal as possible (following the security principle of least privilege) –– only styles (CSS) and scripts (JS) are configured to be allowed/loaded.
> 
> In the sample extension, CSP is set as a `<meta>` tag on [line 118](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/blob/main/frameworks/hello-world-angular/src/panels/HelloWorldPanel.ts#L118) in the `HelloWorldPanel.ts` file.
> 
> Would you mind sharing what your CSP looks like?
> 
> _p.s. this is also likely why the logo.png file is not loading, images are not configured in the hello-world CSP either._

wouaw thanks for this quick reply 👍 but i thought about that too
I commented out this line to make sure it's not that

` private _getWebviewContent(webview: Webview, extensionUri: Uri) {
    // The CSS file from the Angular build output
    const stylesUri = getUri(webview, extensionUri, ["webview-ui", "build", "styles.css"]);
    // The JS files from the Angular build output
    const runtimeUri = getUri(webview, extensionUri, ["webview-ui", "build", "runtime.js"]);
    const polyfillsUri = getUri(webview, extensionUri, ["webview-ui", "build", "polyfills.js"]);
    const mainUri = getUri(webview, extensionUri, ["webview-ui", "build", "main.js"]);

    const nonce = getNonce();

    // Tip: Install the es6-string-html VS Code extension to enable code highlighting below
    /*
    <meta http-equiv="Content-Security-Policy" 
                content="default-src 'self'; style-src ${webview.cspSource}; script-src 'nonce-${nonce}';">
    */
    return /*html*/ `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="stylesheet" type="text/css" href="${stylesUri}">
          <title>Gael</title>
        </head>
        <body>
          <app-root></app-root>
          <script type="module" nonce="${nonce}" src="${runtimeUri}"></script>
          <script type="module" nonce="${nonce}" src="${polyfillsUri}"></script>
          <script type="module" nonce="${nonce}" src="${mainUri}"></script>
        </body>
      </html>
    `;
  }`

**Comment by lastnod** [comment]
in my components.html i sourced my logo.png like this : maybe it is not the right way 
`<a [routerLink]="['/']">
        <img src="./assets/logo.png" alt="logo" title="FrontPage">
      </a>`

**Comment by lastnod** [comment]
i tried with absolute path and it worked but other svg do not load. like from ant design.
i looked at many project on the web. Nobody is using asset folder to load images i think it is because their is a massive issue with relative path in webview

**Comment by hawkticehurst** [comment]
Hi @lastnod!

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) a few days ago on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
