### ISSUE TITLE
JS sample with Vite + React?

### ISSUE THREAD

**Issue by sovetski** [microsoft/vscode-webview-ui-toolkit-samples#177]
Is it possible to add a vanilla JS sample with Vite + React?

We have Vite + React, but it is with TypeScript (https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/frameworks/hello-world-react-vite)

VSCode plugin development is already very difficult, making it with typescript verbose samples is even worse

**Comment by hawkticehurst** [comment]
Hey @sovetski! I'd be open to that!

To be extra clear, however, is your hope that the Vite + React part of the extension (i.e. everything inside the `webview-ui` folder) be vanilla JS or that all code in the extension (everything inside `src` _and_ `webview-ui`) be vanilla JS?

**Comment by sovetski** [comment]
Hi @hawkticehurst, thank you for your quick answer!

To be honest, both `webview-ui` and `src` will be very good.

Because actually, when we want to debug something to understand how it works really (on `src` and other folders), verbose typescript make things more difficult, that is why I think it will be a good idea.

**Comment by hawkticehurst** [comment]
Of course! And sounds good, I'll put it on the backlog to create a sample that's entirely vanilla JS in that case!

And oh yeah interesting, I usually tend to find the typescript/type hints help a lot when developing VS Code extensions but I totally understand how TS can get in the way (there are definitely other areas of web-based programming where I muchhh prefer vanilla JS) so more than happy to offer an option for those who want to avoid TS 😊

**Comment by hawkticehurst** [comment]
Hi @sovetski! 

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) a few days ago on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
