### ISSUE TITLE
Running `vsce package` on Svelte hello-world does not package webview resources to .vsix

### ISSUE THREAD

**Issue by snoop244** [microsoft/vscode-webview-ui-toolkit-samples#179]
### Describe the bug

My extension based on the Svelte hello world project does not package properly into a .vsix. When I open it with a zip utility I can see that the non-webview resources are there (and work fine) but the webview portion (bundle.js and bundle.css) of the vsix are NOT present in the vsix. When I install the vsix and run it, it generates a 404 at runtime.

My extension runs fine in debuge mode (F5) as does the Svelte hello-world project. The webview-ui/public/out resources are present and seem to be properly built, specifically bundle.js and bundle.css.

The same issue is present in both my vsix and the vsix generated from the stock Svelte hello-world project.

I tried adding a "files" section to my root package.json. It had no effect. 

### To reproduce

run `vsce package` on Svelte hello-world project, then install the resulting vsix and attempt to invoke the extension. A blank tab is rendered when the "Howdy" button was expected. The console shows a 404 for the webview assets.

rename the .vsix to .zip. Open it with a zip utility. The Svelte-based assets are not there, while the extension "backend" code is there, as expected.

### Expected behavior

After building a vsix with `vsce package`, I expect to be able to install it and invoke it.

**Comment by hawkticehurst** [comment]
Nice! Happy to hear you were able to figure it out! And thank you also thrilled to hear that the toolkit has been helpful! 😊
