### ISSUE TITLE
Allow to attach debugger to web ui like angular 

### ISSUE THREAD

**Issue by ievgennaida** [microsoft/vscode-webview-ui-toolkit-samples#181]
### Extension/feature description

improve current extension samples to be able to attach debugger for web components like angular. 

### Use case

It would be very helpful to show an example when the vs code runs the extension debug session and attached breakpoints for the SPA apps angular works out of the box in the provided examples.

**Comment by hawkticehurst** [comment]
Hi @ievgennaida, as I just mentioned in the other issue you filed, development on this samples repo has sadly come to close.

Here's the same toolkit deprecation [announcement link](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) where you can learn more details and leave any questions or comments you may have.

And again, thank you so much filing this issue and apologies for never getting around to addressing it.
