### ISSUE TITLE
Update angular sample to the latest angular

### ISSUE THREAD

**Issue by ievgennaida** [microsoft/vscode-webview-ui-toolkit-samples#182]
### Extension/feature description

One of the old angular versions is demonstrated that is outdated, would be nice to see extension example working with up-to-date code.

**Comment by rratchapol** [comment]
❤️

**Comment by hawkticehurst** [comment]
Hi @ievgennaida!

I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) a few days ago on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
