### ISSUE TITLE
Loading React App using Webview giving 401 error

### ISSUE THREAD

**Issue by amitsgaba** [microsoft/vscode-webview-ui-toolkit-samples#183]
Hi Team,

I have created one react app under webview-ui folder in extension code base. Tried to build and main.js and main.css files are creating.

But when i try to load this react app as it shown in https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/frameworks/hello-world-react-cra this example. Getting 401 error. 
I have created Typescript React project it just displays Hello world. 

Able to see the Hello world in browser but not in extension webview.
Here are the screenshot.
<img width="1728" alt="Screenshot 2024-05-20 at 12 29 35" src="https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/17763566/cb732bbc-cd88-492e-84bc-98dc8a6b7253">
<img width="320" alt="Screenshot 2024-05-20 at 12 30 37" src="https://github.com/microsoft/vscode-webview-ui-toolkit-samples/assets/17763566/49768042-d299-480a-9482-160e6c31e260">

**Comment by hawkticehurst** [comment]
Hi @amitsgaba!

I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) a few days ago on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this bug. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
