### ISSUE TITLE
Create Sample Extensions to Demonstrate local resources usage

### ISSUE THREAD

**Issue by cartu38** [microsoft/vscode-webview-ui-toolkit-samples#40]
### Extension/feature description

To demonstrate the toolkit's ability to fetch resources (images,...) from local media folder.

### Use case

Would be nice if weather-webview sample to get sunny, cloudy, ... icons from local media folder.
In other words let's media/main.js function getWeatherIcon(weatherData) get material from local.

**Comment by hawkticehurst** [comment]
Oh wow apologies, I never noticed this issue until right now! But I think that's a great idea, happy to put it onto the backlog.

**Comment by hawkticehurst** [comment]
Hi @cartu38!

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) earlier this week on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
