### ISSUE TITLE
Create sample extension using Angular

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-webview-ui-toolkit-samples#48]
### Sample Extension Description

Implement the default `hello-world` sample extension using Angular to demonstrate how extension authors can scaffold a Angular-based webview extension and use the toolkit with that extension.

**Comment by ignatandrei** [comment]
Is this finish ? I have an Angular site that automates testing for http endpoints ( https://ignatandrei.github.io/BlocklyAutomation/ )  and I want to make available as a VSCode extension. Thanks.

**Comment by hawkticehurst** [comment]
Hey @ignatandrei, creating an Angular sample extension is on our backlog but is not currently being worked on. We have a handful of higher priority items that are being worked on as we move towards releasing `v1.0` of the toolkit and probably won't start on this work until after v1 has been released.

With that said, if you don't want to wait for us you can google "how to use web components within an Angular app" and then also google "how to create a VS Code webview extension that uses Angular" there are a handful of resources and guides that might prove helpful in getting set up.

**Comment by ignatandrei** [comment]
I understand. I do prefer an official supported starter kit ( like the react one). Waiting ....
