### ISSUE TITLE
Notes sample with CustomEditor API

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode-webview-ui-toolkit-samples#60]
### Feature/component description

Can you provide notes example with CustomEditor API like below one

https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/notepad

### Use case

I am creator of [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client) extension, I can't find example how to use CustomEditor api with `virtual document` similar to Notes app

I want to use the following functionality in my extension

- show alert when user is trying to close webview without saving? like in default editor
- Italic title option for readonly mode like in editor
- Dirty Indicator (black dot beside title) for unsaved mode like in default editor

**Comment by rangav** [comment]
related https://github.com/microsoft/vscode-extension-samples/issues/477

**Comment by rangav** [comment]
Any update?

**Comment by hawkticehurst** [comment]
Hi @rangav!

I'm very sorry to say that the toolkit is being deprecated and all development on these samples has come to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) earlier this week on the main toolkit repo where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
