### ISSUE TITLE
Create sample extension using SolidJS

### ISSUE THREAD

**Issue by NateAGeek** [microsoft/vscode-webview-ui-toolkit-samples#66]
Sample Extension Description
Implement the default hello-world sample extension using SolidJs to demonstrate how extension authors can scaffold a SolidJs-based webview extension and use the toolkit with that extension.

**Comment by NateAGeek** [comment]
Awesome! Thank you @hawkticehurst! Great work getting these samples together, actually lead me to clean up a bit of my code now. Hope you have an awesome weekend 🥳

**Comment by hawkticehurst** [comment]
You're welcome and thank you! Hope it's helpful!

Have a great weekend as well 😁
