### ISSUE TITLE
Add docs that provide general directions for using a web framework in webviews

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-webview-ui-toolkit-samples#77]
### Extension/feature description

It would be great if the general ideas/guidance around incorporating a web framework (i.e. React, Vue, etc.) into webview-based extensions were captured in stand-alone documentation for developers to reference.

### Use case

It will be impossible for us to keep up with and maintain an ever-growing catalog of sample extensions that cater to new web frameworks. It would instead be better if the directions on how to use _any_ web framework in webview extensions were provided.

### Misc

I think the currently maintained framework samples (i.e. React) and future planned framework samples (i.e. Svelte, Vue, Angular, and maybe SolidJS) can be still included as a tangible example/reference to aid these docs. But after those are completed I imagine we would no longer actively create/maintain future framework-based samples––only vanilla JS/TS samples.

The one exception that might be considered is if someone from the community contributes a PR with a new web framework sample or a sample demonstrating a helpful scenario/VS Code API in a web framework.

### Reference

I've already [written about this topic a bit on Twitter](https://twitter.com/hawkticehurst/status/1488631890114322432), so hopefully, this can act as a starting point for documentation.

**Comment by hawkticehurst** [comment]
cc @daviddossett for thoughts

**Comment by daviddossett** [comment]
I think this could make sense if it's possible to be broad enough to capture many/most frameworks without needing to endlessly update it.

Perhaps just hitting the on the core concepts and gotchas is a good place to start.

**Comment by vcheeze** [comment]
@hawkticehurst  @daviddossett thanks for the examples you are adding. I've been trying to wrap my head around how to listen to a `postMessage` sent from my extension to my webview in React (with Vite). Can you give me any pointers to this and also include it in the documentation when it comes about?

For context, I've tried adding the `window.addEventListener` call in several places, from the root `index.html`, the `index.tsx`, to the individual page's `useEffect`, but to no avail - the postMessage is being sent from the extension but not being picked up by the event listener in my webview.

Please let me know if I should create a new issue for this instead to keep the issues organized. Thank you!
