### ISSUE TITLE
Angular sample; can't use webview-ui-toolkit UI elements in a form  

### ISSUE THREAD

**Issue by devna13** [microsoft/vscode-webview-ui-toolkit-samples#97]
### Describe the bug

I'm getting errors when I use @vscode/webview-ui-toolkit UI elements in angular form. 

second form generated with basic html elements works fine.

### To reproduce

create a simple from and use it in the app.component.html

\hello-world\webview-ui\src\app\app.component.ts
```
  profileForm = new FormGroup({
    firstName: new FormControl(""),
    lastName: new FormControl(""),
  });

  onSubmit() {
    //console.warn(this.profileForm.value);
    vscode.postMessage({
      command: "form submitted",
      text: this.profileForm.value,
    });
  }
```
\hello-world\webview-ui\src\app\app.component.html
```
  <form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
    <vscode-text-field formControlName="firstName" placeholder="first name"
      >First Name:</vscode-text-field
    >
    <br />
    <vscode-text-field formControlName="lastName" placeholder="last name"
      >Last Name:</vscode-text-field
    >
    <br />
    <vscode-button type="submit" [disabled]="!profileForm.valid">Submit</vscode-button>
  </form>
```
### Screenshots

![image](https://user-images.githubusercontent.com/4080343/191814093-6756125c-8a4a-4610-b59e-878131c05244.png)

![image](https://user-images.githubusercontent.com/4080343/191813910-1eee42bc-73fa-42db-995b-5c4a0b1874ae.png)

![image](https://user-images.githubusercontent.com/4080343/191814093-6756125c-8a4a-4610-b59e-878131c05244.png)

![image](https://user-images.githubusercontent.com/4080343/191839292-3e44293f-8248-43ef-af1f-02b476494f60.png)

**Comment by hawkticehurst** [comment]
Thanks for bug report @devna13!

I've gotten a few other form-related issues on the main toolkit repo so happy to fold this under that work and see if I can find a solution for all of you.
